title: My Classes
description: A place for my Classes, Material, and Tasks
theme: just-the-docs

url: https://SunnyChingSun.github.io/MyClasses

aux_links:
  Template Repository: https://SunnyChingSun.github.io/MyClasses
